import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] })

import { Home } from '@/components/Home/Home';

export const metadata = {
	title: 'Ensaware',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="es-co">
			<body>
				<main>
					<Home>
						{ children }
					</Home>
				</main>
			</body>
		</html>
	)
}
